name: Continous Running

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '50 1 1 1 1'

jobs:
  run_code:
    runs-on: windows-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2.4.2
        
      - name: Set up Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
        
      - name: Run the code
        run: |
          python code1.py
          
      - name: Upload artifact
        uses: actions/upload-artifact@v2.2.2
        with:
          name: my_artifact # 指定 artifact 名称
          path: exchange_rate.csv # 指定要上传的文件路径
          
  download_artifact:
    needs: run_code # 指定依赖的 job
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2.2.2
        with:
          name: my_artifact # 指定要下载的 artifact 名称
      - name: Save artifact to repository directory
        run: |
          mkdir -p artifacts # 创建目录 artifacts
          mv ${{ github.workspace }}/my_artifact artifacts/ # 将 artifact 移动到 artifacts 目录中
