name: Continous Running

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '*/15 * * * *' # 每15分钟运行一次

jobs:
  run_code:
    runs-on: ubuntu-latest
    env:
      EMAIL: '782568799@qq.com' # 指定收件人邮箱地址
      PASSWORD: ${{ secrets.AUTHORIZE }} # 指定发送邮件的邮箱密码或授权码
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: Run the code
        run: |
          nohup python code.py > /dev/null 2>&1 &
        
      - name: Mail CSV File
        uses: dawidd6/action-send-mail@v3
        if: ${{ github.event_name == 'schedule' }}
        with:
          server_address: smtp.qq.com
          server_port: 587
          username: '782568799@qq.com'
          password: ${{ secrets.AUTHORIZE }}
          subject: CSV File
          body: Attached please find the CSV file.
          from: '782568799@qq.com'
          to: '782568799@qq.com'
          attachments: |
            exchange_rate.csv
