name: Continous Running

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 */1 * * *' # 每个整点运行一次

jobs:
  run_code:
    runs-on: ubuntu-latest
    env:
      EMAIL: ${{ secrets.EMAIL }} # 指定收件人邮箱地址
      PASSWORD: ${{ secrets.PASSWORD }} # 指定发送邮件的邮箱密码或授权码
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: Run the code
        run: |
          nohup python code.py > /dev/null 2>&1 &
        
      - name: Mail CSV File
        uses: dawidd6/action-send-mail@v3
        if: ${{ github.event_name == 'schedule' && contains( format('{0:%H}', github.event.head_commit.timestamp), ['00', '01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11'] ) }}
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL }}
          password: ${{ secrets.PASSWORD }}
          subject: CSV File
          body: Attached please find the CSV file.
          from: ${{ secrets.EMAIL }}
          to: ${{ env.EMAIL }}
          attachments: |
            exchange_rate.csv
