name: Continous Running

on:
  push:
    branches: [ main ]
  schedule:
      - cron: '50 1 1 1 1'
#     - cron: '*/15 * * * *' # 每15分钟运行一次

jobs:
  run_code:
    runs-on: ubuntu-latest
    env:
      EMAIL: '782568799@qq.com' # 指定收件人邮箱地址
      PASSWORD: ${{ secrets.AUTHORIZE }} # 指定发送邮件的邮箱密码或授权码
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
        
      - name: Run the code
        run: |
          nohup python code.py > /dev/null 2>&1 &
        
